import { TEmployeeSample } from "types/employee";

export const data: TEmployeeSample[] = [
  {
    _id: "63b42e5d832740f87f4836e7",
    name: "Brock Hanson",
    role: "Department Head",
    department: "Engineering",
    email: "brockhanson@shopabout.com",
  },
  {
    _id: "63b42e5d46ac79cbfb922dd5",
    name: "Shawn Lowery",
    role: "Department Head",
    department: "Engineering",
    email: "shawnlowery@shopabout.com",
  },
  {
    _id: "63b42e5ddafd8fe7794e3fe8",
    name: "Justice Holt",
    role: "Supervisor",
    department: "Research & Development",
    email: "justiceholt@shopabout.com",
  },
  {
    _id: "63b42e5dfd8d31eb694672e4",
    name: "Reva Estes",
    role: "Supervisor",
    department: "Manufacturing",
    email: "revaestes@shopabout.com",
  },
  {
    _id: "63b42e5d1e858e83f3ad314c",
    name: "Florine Lloyd",
    role: "Manager",
    department: "Engineering",
    email: "florinelloyd@shopabout.com",
  },
  {
    _id: "63b42e5d25bc801e809278a9",
    name: "Anne Burris",
    role: "Supervisor",
    department: "Manufacturing",
    email: "anneburris@shopabout.com",
  },
  {
    _id: "63b42e5dffe7f959ec31081d",
    name: "Baker Kelley",
    role: "Supervisor",
    department: "Research & Development",
    email: "bakerkelley@shopabout.com",
  },
  {
    _id: "63b42e5d38b1a2fce0164e24",
    name: "Roth Curtis",
    role: "Department Head",
    department: "Manufacturing",
    email: "rothcurtis@shopabout.com",
  },
  {
    _id: "63b42e5d93415fd8f7c7dec0",
    name: "Cooper Orr",
    role: "Department Head",
    department: "Research & Development",
    email: "cooperorr@shopabout.com",
  },
  {
    _id: "63b42e5d2ee1759e1dd52f6c",
    name: "Delaney Hammond",
    role: "Supervisor",
    department: "Research & Development",
    email: "delaneyhammond@shopabout.com",
  },
  {
    _id: "63b42e5d6db7728324063ec0",
    name: "Brandy Gibson",
    role: "Supervisor",
    department: "Manufacturing",
    email: "brandygibson@shopabout.com",
  },
  {
    _id: "63b42e5dda7d64189fccf8a2",
    name: "Crosby Hurley",
    role: "Department Head",
    department: "Research & Development",
    email: "crosbyhurley@shopabout.com",
  },
  {
    _id: "63b42e5d179696f1423ac80d",
    name: "Jackson Clark",
    role: "Department Head",
    department: "Research & Development",
    email: "jacksonclark@shopabout.com",
  },
  {
    _id: "63b42e5d8daf3871f9c7185a",
    name: "Paulette Norton",
    role: "Manager",
    department: "Manufacturing",
    email: "paulettenorton@shopabout.com",
  },
  {
    _id: "63b42e5d0109d9b6de127a8c",
    name: "Meagan Hurst",
    role: "Manager",
    department: "Research & Development",
    email: "meaganhurst@shopabout.com",
  },
  {
    _id: "63b42e5d9c9bf56fb06c8c3a",
    name: "Jami Cook",
    role: "Manager",
    department: "Manufacturing",
    email: "jamicook@shopabout.com",
  },
  {
    _id: "63b42e5deff7e822cf2e1f78",
    name: "Virgie Howell",
    role: "Supervisor",
    department: "Engineering",
    email: "virgiehowell@shopabout.com",
  },
  {
    _id: "63b42e5d871e63806e9fce58",
    name: "Karina Goodwin",
    role: "Supervisor",
    department: "Engineering",
    email: "karinagoodwin@shopabout.com",
  },
  {
    _id: "63b42e5da0aefcca0e6f7306",
    name: "Dora Acevedo",
    role: "Department Head",
    department: "Engineering",
    email: "doraacevedo@shopabout.com",
  },
  {
    _id: "63b42e5d339769ddc8262bf7",
    name: "Mcmahon Williams",
    role: "Department Head",
    department: "Research & Development",
    email: "mcmahonwilliams@shopabout.com",
  },
];

// [
//   "{{repeat(20, 20)}}",
//   {
//     _id: "{{objectId()}}",
//     name: "{{firstName()}} {{surname()}}",
//     role: '{{random("Department Head", "Supervisor", "Manager" )}}',
//     department:
//       '{{random("Research & Development", "Engineering", "Manufacturing" )}}',
//     email: "{{email()}}",
//   },
// ]
